# Generated by Django 4.0.5 on 2022-06-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likeproduct',
            name='is_like',
            field=models.BooleanField(default=False),
        ),
    ]
